version: '3'

networks:
  lan:

services:

  db:
    image: neo4j:3.3.1-enterprise
    container_name: recipe-ideas-db
    networks:
      - lan
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    volumes:
      - /opt/dev/IdeaProjects/recipes/DB/core1/conf:/var/lib/neo4j/conf
      - /opt/dev/IdeaProjects/recipes/DB/core1/data:/var/lib/neo4j/data
      - /opt/dev/IdeaProjects/recipes/DB/core1/logs:/logs
      - /opt/dev/IdeaProjects/recipes/DB/core1/plugins:/plugins
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_mode=SINGLE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687

  backend:
    image: recipe-ideas-backend:0.1
    container_name: recipe-ideas-backend
    networks:
      - lan
    ports:
      - 9000:9000