#!/usr/bin/env bash

sbt clean assembly

docker build \
    --no-cache \
    -f docker/backend/Dockerfile \
    -t recipe-ideas-backend:0.1 \
    .

for id in $(docker images --filter "dangling=true" -q) ; do
    docker rmi ${id}
done